INSERT IGNORE INTO schemes (id, name, description, eligible_states, max_land_size_acres, max_annual_income, eligible_categories, application_url, is_active) VALUES
(1, 'Namo Shetkari Maha Samman Nidhi Yojana', 'Financial assistance of Rs. 6000 per year directly to the bank accounts of farmers in Maharashtra, as an addition to PM-KISAN.', 'Maharashtra', 5.0, 200000.0, 'ALL', 'https://nsmsny.mahaonline.gov.in/', true),
(2, 'Magel Tyala Shet Tale', '100% subsidy scheme for construction of farm ponds to help farmers secure water for irrigation.', 'Maharashtra', 10.0, 500000.0, 'ALL', 'https://mahadbtmahait.gov.in/', true),
(3, 'Bhausaheb Fundkar Phalbag Lagvad Yojana', 'Subsidy for the plantation of fruit orchards to boost farmers alternative income.', 'Maharashtra', 5.0, 150000.0, 'ALL', 'https://mahadbtmahait.gov.in/', true),
(4, 'Gopinath Munde Shetkari Apghat Vima Yojana', 'Insurance cover up to Rs. 2 Lakhs to the families of farmers in case of accidental death or disability.', 'Maharashtra', 50.0, 1000000.0, 'ALL', 'https://www.maharashtra.gov.in/', true),
(5, 'Nanaji Deshmukh Krishi Sanjeevani Yojana (PoCRA)', 'Promoting climate-resilient agriculture among small and marginal farmers in drought-prone villages.', 'Maharashtra', 4.9, 150000.0, 'SC, ST, OPEN', 'https://pocra.gov.in/', true),
(6, 'Dr. Babasaheb Ambedkar Krishi Swavalamban Yojana', 'Provides financial aid for new wells, pump sets, and micro-irrigation systems specifically for SC/ST farmers.', 'Maharashtra', 6.0, 150000.0, 'SC, ST', 'https://mahadbtmahait.gov.in/', true),
(7, 'Vahatuk Anudan Yojana (Transport Subsidy)', 'Subsidy for transporting agricultural commodities to markets under the Maharashtra State Agriculture Marketing Board.', 'Maharashtra', 10.0, 300000.0, 'ALL', 'https://www.msamb.com/', true),
(8, 'Birsa Munda Krishi Kranti Yojana', 'Dedicated scheme similar to Swavalamban Yojana providing irrigation facilities to ST category farmers.', 'Maharashtra', 6.0, 150000.0, 'ST', 'https://mahadbtmahait.gov.in/', true),
(9, 'Kanda Chal Ubharni Anudan (Onion Storage)', 'Subsidy for building scientific onion storage structures to prevent post-harvest rotting and distress sales.', 'Maharashtra', 15.0, 500000.0, 'ALL', 'https://mahadbtmahait.gov.in/', true),
(10, 'Shetkari Masik Pension Yojana (Proposed/Draft)', 'Drafted scheme to provide a monthly pension of Rs. 3000 to elderly farmers above 60 years.', 'Maharashtra', 2.0, 50000.0, 'ALL', 'https://agri.maharashtra.gov.in/', true);
